### ISSUE TITLE
After to setup of the requirements, how to install? Is it necessary a sudo user?

### ISSUE THREAD

**Issue by nickolasmenezes** [stajichlab/AAFTF#11]
Hi dear all, 

I'm trying to use, but I did not find instructions to setup the AAFTF after the requirements. 
I cloned the repository and added to the path, but did not work. 
Could you please send me some instructions?

Thank you.
Kind regards
Nickolas

**Comment by hyphaltip** [comment]
For now, until I finish making a conda package, is you just need to make sure the 'scripts' folder is in  your PATH. eg
on my system we have the folder `/folder/to/AAFTF/scripts` added to PATH. 

Did you also install dependencies? At a minimum you need SPAdes, pilon, ncbi-blast, BBMap, and samtools -- alternative trimmomatic.

**Comment by nickolasmenezes** [comment]
Hi @hyphaltip 

Thanks a lot. Conda package will be great. Congratulations. 
I had set the path to /folder/to/AAFTF/. Now, it's working.
Maybe you can add this information in the Readme.txt. 

Yes, I configured all dependencies already. 
Kind regards.

**Comment by hyphaltip** [comment]
will be adding more - I don't consider this an official release yet so I have not finished the packaging and documentation intended to be used by a broader user base just yet but I can add to the docs. Not enough time in the day to keep up with all these needs, sorry!

**Comment by nickolasmenezes** [comment]
Don't worry. I can understand. 
You do a great job. 
Marcus Teixeira recommends this pipeline to me. 
Good Luck
