### ISSUE TITLE
sourmash LCA database update url?

### ISSUE THREAD

**Issue by nextgenusfs** [stajichlab/AAFTF#15]
Seems that at some point sourmash newer version requires an updated LCA database, I got failure with v4.2.2 and the one we have pinned in resources.py.  New link is https://osf.io/9xdg2/download and page is https://sourmash.readthedocs.io/en/latest/databases.html

**Comment by ctb** [comment]
hi! reminded of this by https://twitter.com/jonpalmer2013/status/1521312530936725506 :)

we did just release new databases! it would be easy for me to build you a new Genbank LCA (or give you the commands to do it), or you could just use the GTDB ones.

**Comment by ctb** [comment]
(as of sourmash v4.4, scheduled soon, we can also point you at larger-on-disk but much faster and lower memory SQLite-based LCA database.)

**Comment by hyphaltip** [comment]
thanks i was trying some thing before and it was way too slow for us to put on but I want to give this another go.

Noting that our current 'sourpurg' w sourmash did about as good a job as NCBI's now available screening tool in a fraction of the time and a lot less data to download..

**Comment by ctb** [comment]
k - let us know how we can help! would AAFTF be something we can just download and run on our own, if we feel so inclined to try it out?

**Comment by hyphaltip** [comment]
sure - is very simple python package and certainly welcome someone else helping me package it up for conda properly...

**Comment by hyphaltip** [comment]
have implemented, it doesn't seem to really work as well as the old genbank-k31 though
with gtdb or gtdb-reps 
```
CMD: sourmash lca classify --db /srv/projects/db/AAFTF_DB/gtdb-
        rs207-genomic-reps.dna.k31.lca.json.gz --query assembly.fasta.sig
[May 29 11:18 AM] Found 0 taxonomic classifications for contigs:
```
With old scheme.
```
CMD: sourmash lca classify --db
        /srv/projects/db/AAFTF_DB/genbank-k31.lca.json.gz --query
        assembly.fasta.sig
[May 29 11:17 AM] Found 2 taxonomic classifications for contigs:
Eukaryota;Ascomycota;Dothideomycetes;Capnodiales;Cladosporiaceae;Rachicladosporium;Rachicladosporium antarcticum
Eukaryota;Ascomycota;Dothideomycetes;Capnodiales;Cladosporiaceae;Rachicladosporium
```

@ctb is this because the gtdb is really bacteria only? I think this is okay in a sense but I guess DBs are too large now to really do a single sourmash search on representative dbs?

**Comment by hyphaltip** [comment]
Of course. I can send some directions. It has a test set I can share if it’s not in there now. Not had a lot of dev time lately but this would be easy. There’s a config file with dictionary that sets the download url for the sourmash db.

**Comment by hyphaltip** [comment]
This has been fixed now, it downloads automatically into $AAFTF_DB (either env variable or cmdline option) to save this DB. There are also options to run against GTDB databases as indexed by sourmash tools of @ctb and @sourmash-bio relying on LCA index files listed https://sourmash.readthedocs.io/en/latest/databases.html#gtdb-r08-rs214-dna-databases in addition the LCA for genbank 2017 which actually works really well for finding bacteria contamination and is fast to search https://sourmash.readthedocs.io/en/latest/legacy-databases.html#genbank-microbial-genomes-lca
