### ISSUE TITLE
AAFTF pipeline always fails at vecscreen step

### ISSUE THREAD

**Issue by rfitak** [stajichlab/AAFTF#19]
I had no issues running each step of the pipeline independently, but when I tried to run AAFTF in pipeline mode it always failed at the vecscreen step.  Turns out there is just a simply typo on line 137 in the `pipeline.py` script.  Can you remove the space?

```python
# please change
    if not checkfile(basename + ' .vecscreen.fasta'):
# to
    if not checkfile(basename + '.vecscreen.fasta'):
```

**Comment by hyphaltip** [comment]
okay thank will fix - I rarely use pipeline mode so sorry for not testing that better.

**Comment by hyphaltip** [comment]
Fixed - will push new release
