### ISSUE TITLE
Support single-end and interleaved fastq data

### ISSUE THREAD

**Issue by hyphaltip** [stajichlab/AAFTF#2]
Support single ended read data for cleanup and assembly.

Support interleaved read data - may still have to split into fwd and rev but the program should do this not require the user.

**Comment by hyphaltip** [comment]
This is mostly supported but still some kinks to work out as to whether or not Pilon can be supported or depth of coverage assessment reporting in sourpurge

**Comment by nextgenusfs** [comment]
I think Pilon requires PE reads.

**Comment by hyphaltip** [comment]
single end works for many steps and merged reads can be given to spades along with paired end.
