### ISSUE TITLE
AAFTF pipeline exiting when mito fails

### ISSUE THREAD

**Issue by Kata-Pa** [stajichlab/AAFTF#26]
Hello,

Is it possible to run the AAFTF pipeline, skipping the mito step? I get an error from Novoplasty about invalid seed, which is not true, so it might be that no mitochondrial reads are present. Is there  a way to make the pipeline ignore the mito step and continue with the rest?

Thank you in advance.

**Comment by hyphaltip** [comment]
No need to run that step unless you want the mt genome. Just run filter and
assemble the steps are intended to be pick and choose

Sent from Gmail Mobile
***@***.***
Jason Stajich - UC Riverside
http://lab.stajich.org

**Comment by Kata-Pa** [comment]
Yes, of course this is an option, but instead of running each step separately, I was just wondering if the **AAFTF pipeline** command could be run directly with some parameter to skip one or more of the steps in between. In my case for example, I am interested in all the steps (1-9), except for the mito (step 2). If that is not possible and I want the whole pipeline, I have to run trim, filter and assemble but also vecscreen, rmdup, pilon, sort and assess. Do I interpret this right?

**Comment by hyphaltip** [comment]
sure it is always possible to develop another function or option to the
pipeline all in one command but isn't my current use cases so I don't know
when this will get attention right now.
the whole point is you get to mix and match the steps you might run with
the individual commands so you aren't bound to the "pipeline" command
assumptions by any means.

here's an example of job script I use to run AAFTF that doesn't run mito
https://github.com/stajichlab/KassonLab_Nectriaceae/blob/main/pipeline/asm/01_AAFTF.sh
here's one for Mito
https://github.com/stajichlab/KassonLab_Nectriaceae/blob/main/pipeline/asm/03_mito.sh

---
Jason E Stajich, PhD
Professor and Vice-Chair, Dept of Microbiology and Plant Pathology
University of California, Riverside

Fellow, CIFAR Fungal Kingdom: Threats and Opportunities
<https://www.cifar.ca/research/program/fungal-kingdom>
email: ***@***.***
twitter: @stajichlab <http://twitter.com/stajichlab> @hyphaltip
<http://twitter.com/hyphaltip> @zygolife <http://twitter.com/zygolife>
website: http://lab.stajich.org
office: +1 951.827.2363 mobile: +1 909.333.6709
